/* Fallback sample content — used automatically if the backend API can't be reached,
   so the site always renders something even without the server running. */
const FALLBACK_REELS = [
  { id:1, title:"5 ChatGPT prompts that save me 10hrs/week", desc:"The exact prompt formulas I use for planning, writing and research.", cat:"chatgpt", catLabel:"ChatGPT", views:"612K", likes:"48K", date:"1d ago", img:"https://images.unsplash.com/photo-1531746790731-6c087fecd65a?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:2, title:"Automate your inbox with AI in 5 minutes", desc:"Set up a zero-effort email triage system using GPT + Zapier.", cat:"automation", catLabel:"Automation", views:"389K", likes:"31K", date:"2d ago", img:"https://images.unsplash.com/photo-1596526131083-e8c633c948d2?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:3, title:"This AI tool builds websites in 60 seconds", desc:"A hands-on look at the fastest AI website builder I've tested.", cat:"websites", catLabel:"Websites", views:"1.2M", likes:"96K", date:"3d ago", img:"https://images.unsplash.com/photo-1547658719-da2b51169166?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:4, title:"Notion + AI: my exact second brain setup", desc:"How I organize projects, notes and tasks with AI-assisted Notion.", cat:"productivity", catLabel:"Productivity", views:"455K", likes:"38K", date:"4d ago", img:"https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:5, title:"Top 7 AI tools nobody's talking about yet", desc:"Underrated tools that quietly outperform the popular ones.", cat:"ai-tools", catLabel:"AI Tools", views:"780K", likes:"61K", date:"4d ago", img:"https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:6, title:"Full ChatGPT tutorial for total beginners", desc:"Everything you need to know to start using ChatGPT the right way.", cat:"tutorials", catLabel:"Tutorials", views:"920K", likes:"71K", date:"5d ago", img:"https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:7, title:"The 2-minute AI trick to write better captions", desc:"A tiny prompt tweak that instantly improves your social copy.", cat:"tips", catLabel:"Tips & Tricks", views:"334K", likes:"28K", date:"6d ago", img:"https://images.unsplash.com/photo-1655720031554-a929595ffad7?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:8, title:"Build a personal AI assistant with no code", desc:"Step-by-step: connect GPT to your calendar, tasks and notes.", cat:"automation", catLabel:"Automation", views:"501K", likes:"42K", date:"6d ago", img:"https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:9, title:"I let AI plan my entire week — here's what happened", desc:"An honest experiment handing my calendar over to an AI agent.", cat:"productivity", catLabel:"Productivity", views:"667K", likes:"55K", date:"1w ago", img:"https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:10, title:"3 AI tools that replaced my entire team", desc:"How solo creators are shipping like small studios in 2026.", cat:"ai-tools", catLabel:"AI Tools", views:"1.1M", likes:"88K", date:"1w ago", img:"https://images.unsplash.com/photo-1526378787940-576a539ba69d?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:11, title:"Landing pages in minutes with AI website builders", desc:"Comparing three tools so you don't have to test them yourself.", cat:"websites", catLabel:"Websites", views:"298K", likes:"22K", date:"1w ago", img:"https://images.unsplash.com/photo-1559028012-481c04fa702d?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" },
  { id:12, title:"Prompt engineering in plain English", desc:"A tutorial that finally makes prompting click for beginners.", cat:"tutorials", catLabel:"Tutorials", views:"812K", likes:"64K", date:"2w ago", img:"https://images.unsplash.com/photo-1550439062-609e1531270e?q=80&w=600&auto=format&fit=crop", link:"https://instagram.com" }
];

const FALLBACK_BLOGS = [
  { id:1, title:"The State of AI in 2026: What Actually Changed", excerpt:"Cutting through the hype to look at what genuinely shifted for creators and businesses this year.", cat:"ai-news", catLabel:"AI News", time:"7 min read", date:"Jun 28, 2026", img:"https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=700&auto=format&fit=crop" },
  { id:2, title:"10 AI Tools Worth Paying For (And 5 That Aren't)", excerpt:"A no-nonsense breakdown of which AI subscriptions actually earn their spot in your stack.", cat:"ai-tools", catLabel:"AI Tools", time:"9 min read", date:"Jun 21, 2026", img:"https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=700&auto=format&fit=crop" },
  { id:3, title:"How to Build Your First AI Automation, Step by Step", excerpt:"A beginner-friendly walkthrough of connecting your first no-code AI workflow.", cat:"tutorials", catLabel:"Tutorials", time:"12 min read", date:"Jun 14, 2026", img:"https://images.unsplash.com/photo-1516110833967-0b5716ca1387?q=80&w=700&auto=format&fit=crop" },
  { id:4, title:"The Productivity Stack I Actually Use Daily", excerpt:"Every app, prompt and shortcut in my real daily workflow — no filler.", cat:"productivity", catLabel:"Productivity", time:"6 min read", date:"Jun 7, 2026", img:"https://images.unsplash.com/photo-1483058712412-4245e9b90334?q=80&w=700&auto=format&fit=crop" },
  { id:5, title:"How Small Businesses Are Quietly Winning with AI", excerpt:"Real examples of small teams using AI to compete with much bigger budgets.", cat:"business", catLabel:"Business", time:"8 min read", date:"May 30, 2026", img:"https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=700&auto=format&fit=crop" },
  { id:6, title:"Automation Isn't Scary: A Practical Starter Guide", excerpt:"Why 'automation' sounds harder than it is, and where to actually begin.", cat:"automation", catLabel:"Automation", time:"7 min read", date:"May 22, 2026", img:"https://images.unsplash.com/photo-1591453089816-0fbb971b454c?q=80&w=700&auto=format&fit=crop" },
  { id:7, title:"Inside the AI Tools Changing How We Write", excerpt:"A look at the newest writing assistants and where they genuinely help.", cat:"ai-tools", catLabel:"AI Tools", time:"5 min read", date:"May 15, 2026", img:"https://images.unsplash.com/photo-1455390582262-044cdead277a?q=80&w=700&auto=format&fit=crop" },
  { id:8, title:"AI News Roundup: The Launches That Mattered", excerpt:"Skipping the noise to cover the handful of releases worth your attention.", cat:"ai-news", catLabel:"AI News", time:"6 min read", date:"May 8, 2026", img:"https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=700&auto=format&fit=crop" }
];

const FALLBACK_TOOLS = [
  { id:1, name:"PromptForge", cat:"Prompt Engineering", rating:4.8, desc:"Build, test and version your prompts like code — with built-in A/B comparisons.", initial:"P", link:"#" },
  { id:2, name:"FlowPilot", cat:"Automation", rating:4.7, desc:"Drag-and-drop AI workflows connecting your favorite apps in minutes.", initial:"F", link:"#" },
  { id:3, name:"NoteMind", cat:"Productivity", rating:4.6, desc:"An AI second brain that organizes notes, tasks and ideas automatically.", initial:"N", link:"#" },
  { id:4, name:"SiteCraft AI", cat:"Website Builder", rating:4.5, desc:"Describe your site in plain English and get a launch-ready page.", initial:"S", link:"#" },
  { id:5, name:"ClipGenius", cat:"Content Creation", rating:4.7, desc:"Turns long videos into short, caption-ready clips automatically.", initial:"C", link:"#" },
  { id:6, name:"InboxZero AI", cat:"Automation", rating:4.4, desc:"Triages, drafts and schedules your email replies while you focus elsewhere.", initial:"I", link:"#" }
];

const FALLBACK_TESTIMONIALS = [
  { id:1, text:"Sid's reels are the only AI content I actually finish watching. Practical, no fluff, and I use something from almost every video.", name:"Ananya Rao", role:"Product Designer", img:"https://randomuser.me/api/portraits/women/68.jpg" },
  { id:2, text:"I automated half my content workflow after one blog post. Growing With Sid pays for itself in saved hours every single week.", name:"Marcus Lee", role:"Freelance Creator", img:"https://randomuser.me/api/portraits/men/32.jpg" },
  { id:3, text:"Finally, someone who explains AI without the jargon. My whole team follows the newsletter now.", name:"Priya Nair", role:"Marketing Lead, Loopwave", img:"https://randomuser.me/api/portraits/women/44.jpg" },
  { id:4, text:"The tool reviews alone have saved me from at least three bad subscriptions. Honest, sharp, and always useful.", name:"Daniel Kim", role:"Indie Hacker", img:"https://randomuser.me/api/portraits/men/76.jpg" }
];

const FALLBACK_POSTS = [
  { id:1, caption:"Swipe for the 5-step framework I use to automate literally any repetitive task with AI.", cat:"automation", catLabel:"Automation", type:"Carousel · 6 slides", likes:"22.4K", comments:"312", date:"6h ago", img:"https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=800&auto=format&fit=crop", link:"https://instagram.com" },
  { id:2, caption:"The only 3 ChatGPT settings that actually matter. Save this before you forget.", cat:"chatgpt", catLabel:"ChatGPT", type:"Single image", likes:"31.8K", comments:"540", date:"1d ago", img:"https://images.unsplash.com/photo-1531746790731-6c087fecd65a?q=80&w=800&auto=format&fit=crop", link:"https://instagram.com" },
  { id:3, caption:"My entire AI tool stack for 2026, ranked from 'life-changing' to 'meh'.", cat:"ai-tools", catLabel:"AI Tools", type:"Carousel · 8 slides", likes:"45.1K", comments:"789", date:"1d ago", img:"https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=800&auto=format&fit=crop", link:"https://instagram.com" },
  { id:4, caption:"A simple Notion + AI dashboard template you can duplicate in 2 minutes. Link in bio.", cat:"productivity", catLabel:"Productivity", type:"Single image", likes:"18.7K", comments:"204", date:"2d ago", img:"https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=800&auto=format&fit=crop", link:"https://instagram.com" },
  { id:5, caption:"How I designed and shipped this landing page with AI in one afternoon, no code.", cat:"websites", catLabel:"Websites", type:"Carousel · 5 slides", likes:"27.3K", comments:"365", date:"2d ago", img:"https://images.unsplash.com/photo-1547658719-da2b51169166?q=80&w=800&auto=format&fit=crop", link:"https://instagram.com" },
  { id:6, caption:"A beginner's map of every type of AI model you'll hear about this year, explained simply.", cat:"tutorials", catLabel:"Tutorials", type:"Carousel · 7 slides", likes:"39.6K", comments:"612", date:"3d ago", img:"https://images.unsplash.com/photo-1550439062-609e1531270e?q=80&w=800&auto=format&fit=crop", link:"https://instagram.com" },
  { id:7, caption:"The one-line prompt trick that instantly makes ChatGPT's answers more useful.", cat:"tips", catLabel:"Tips & Tricks", type:"Single image", likes:"15.2K", comments:"178", date:"3d ago", img:"https://images.unsplash.com/photo-1655720031554-a929595ffad7?q=80&w=800&auto=format&fit=crop", link:"https://instagram.com" },
  { id:8, caption:"Behind the scenes of building my no-code AI assistant — the wins and the failures.", cat:"automation", catLabel:"Automation", type:"Carousel · 4 slides", likes:"24.9K", comments:"298", date:"4d ago", img:"https://images.unsplash.com/photo-1485827404703-89b55fcc663e?q=80&w=800&auto=format&fit=crop", link:"https://instagram.com" },
  { id:9, caption:"This is what a fully AI-planned week actually looks like, hour by hour.", cat:"productivity", catLabel:"Productivity", type:"Carousel · 6 slides", likes:"33.4K", comments:"421", date:"5d ago", img:"https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=800&auto=format&fit=crop", link:"https://instagram.com" }
];

const BRANDS = ["Notion","Zapier","Framer","Vercel","Linear","OpenAI","Superhuman","Runway"];
